#!/bin/bash

DIR=`pwd`

# SHELL
$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)
ln -s $DIR/.zshrc ~/.zshrc

# TMUX
ln -s $DIR/.tmux.conf ~/.tmux.conf
ln -s $DIR/.tmux-airline ~/.tmux-airline

# VIM
mkdir -p ~/.vim/autoload
ln -s $DIR/.vimrc ~/.vimrc
vim +PlugInstall +qall

# GIT
ln -s $DIR/.gitconfig ~/.gitconfig

# Fonts
sudo ln -s $DIR/etc/fonts/local.conf /etc/fonts/local.conf
mkdir -p ~/.local/share/fonts
ln -s $DIR/.fonts/* ~/.local/share/fonts/

# Keyboard setting
ln -s $DIR/.xmodmaprc ~/.xmodmaprc

# Xresources
ln -s $DIR/.Xresources ~/.Xresources
ln -s $DIR/.xinitrc ~/.xinitrc

# i3
mkdir ~/.i3
ln -s $DIR/.i3/* ~/.i3/

# bin
mkdir ~/bin
ln -s $DIR/bin/* ~/bin
